config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # Skip sessions/registration to limit authentication to oauth
  # Signout and sign_in(GET/CREATE) need to be implemented separately.
  # :authenticate_user! redirects user to sign_in GET !
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' },
                     skip: %i[sessions registration]
  as :user do
    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resource :cv, only: [:new, :create, :edit, :update]
  resource :profile_picture, only: [:new, :create, :edit, :update]

  get 'welcome/profile'
  root 'welcome#index'

  namespace :admins  do
    get 'dashboard', to: 'applicants#dashboard', as: 'dashboard'
    get 'dashboard/:status', to: 'applicants#dashboard_filter', as: 'applicant_status'
    resources :applicants, except: [:edit, :index, :destroy, :new, :create, :update] do
      resources :comments
    end
    get 'decision/:status/:decision', to: 'applicants#status_update', as: 'decision'
    post 'search', to: 'applicants#search', as: 'applicant_search'
    resources :options, except: [:show, :index, :destroy],
              path_names: { new: 'new/:category', edit: ':category' } do
      get ':category', to: 'options#filter', as: 'filter', on: :collection
      delete ':category/:id', to: 'options#destroy', as: 'destroy', on: :collection
    end
    resources :drts, only: [:new, :create], path_names: { new: '/', create: 'new/'}
    get 'interview', to: 'interview#new', as: 'interview'
    resources :interview, only: [:create, :edit, :update, :show], path_names: { new: '/', create:'new/'}
  end
  resources :applicants, except: [:edit, :destroy, :update, :show] do
  end
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  def to_s
    first_name + " " + last_name
  end

  has_one :cv, dependent: :destroy
  has_one :profile_picture, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_one :drt, dependent: :destroy
  has_one :interview, dependent: :destroy

  validates_presence_of :first_name,
                        :last_name,
                        :email_address,
                        :phone_number,
                        :highest_education,
                        :english_knowledge,
                        message: I18n.t('form.blank')

  validates_length_of :first_name,
                      :last_name,
                      allow_blank: true,
                      minimum: 2,
                      maximum: 35,
                      message: I18n.t('form.length', min: 3, max: 35)

  validates_length_of :phone_number,
                      allow_blank: true,
                      in: 10..15,
                      message: I18n.t('form.length', min: 10, max: 15)

  validates_presence_of :english_class,
                        :payment_option,
                        message: I18n.t('form.select')

  validates_numericality_of :phone_number,
                            allow_blank: true,
                            only_integer: true,
                            message: I18n.t('form.only_numbers')

  validates_format_of :email_address,
                      with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
                      allow_blank: true,
                      message: I18n.t('form.email_format')

  scope :find_applicant_by_name_or_email, ->(names, email) {
                                            where('first_name RLIKE ? OR
                                            last_name RLIKE ? OR
                                            email_address RLIKE ?',
                                            names, names, email)
                                          }

  scope :needs_drt, -> {
                         joins(:cv, :profile_picture)
                           .where(
                             status: 'basic',
                             cvs: { upload_state: 'approved' },
                             profile_pictures: { upload_state: 'approved' }
                           ).left_outer_joins(:drt)
                            .where(
                             drts: { applicant_id: nil }
                            )
                       }

  def assign_drt
    self.drt = Drt.where(applicant_id: nil).first
    unless drt
      errors.add(:base, 'Applicant could not be assigned DRT. Add new DRTs!')
      throw :abort
    end
    save
    self.next if status == 'basic'
    ExampleMailer.sample_email(self).deliver_now
  end

  before_save do
    if status == 'drt'
      throw :abort unless cv_pp_approved?
      assign_drt unless drt
    elsif status == 'interview'
      Interview.create(applicant_id: id) unless interview
    end
  end

  state_machine :status, initial: :basic do
    event :next do
      transition basic: :drt, drt: :interview
    end

    event :decline do
      transition all: :declined
    end
  end

  private

  def cv_pp_approved?
    (cv && profile_picture) &&
      cv.upload_state == 'approved' &&
      profile_picture.upload_state == 'approved'
  end
end

app/controllers/admins/applicants_controller.rb
class Admins::ApplicantsController < Admins::AdminController
  def dashboard
    @applicants = Applicant.all
  end

  def dashboard_filter
    @applicants = Applicant.where(status: params[:status])
  end

  def status_update
    applicant = Applicant.find(params[:applicant_id])
    applicant.send(params[:status]).send(params[:decision])
    flash[:danger] = applicant.errors.full_messages.first if applicant.errors.any?
    redirect_back fallback_location: root_path
  end

  def show
    @applicant = Applicant.find(params[:id])
    @commentable = Applicant.find(params[:id])
    @comment = Comment.new
    @comments = Comment.where(commentable_id: @applicant.id)
  end

  def search
    @applicants = Applicant.find_applicant_by_name_or_email(search_params, params[:search][:search_term])
  end

  private

  def search_params
    params.require(:search).permit(:search_term)
    params[:search][:search_term].split(' ').join('|')
  end
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  helper_method :get_name, :get_name_and_message

  def get_name(category)
    Option.where(category: category).pluck(:name)
  end

  def get_name_and_message(category)
    Option.where(category: category).pluck(:message, :name)
  end

  def new
    @applicant = Applicant.new
  end

  def create
    @applicant = current_user.create_applicant(applicant_params)
    if @applicant.save
      flash[:success] = I18n.t('flash.application_success')
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def applicant_params
    params.require(:applicant).permit(:first_name, :last_name, :email_address, :phone_number, :highest_education, :english_knowledge, :english_class, :payment_option)
  end
end

app/views/admins/applicants/_applicant_table.html.haml
.container
  .table-responsive.transparent-container
    %table.table
      %thead
        %tr
          %th Name
          %th Email Address
          %th Status
          %th Action
          %th When
      - @applicants.each do |a|
        %tr
          %td= link_to (a.first_name + ' ' + a.last_name).to_str, admins_applicant_path(id: a.id)
          %td #{a.email_address}
          %td= status_string(a.status)
          %td= status_button(a)
          %td= time_ago_in_words(a.updated_at) + ' ago'

app/views/admins/applicants/_header.html.haml
.navbar.navbar-default.admin-header
  %ul.nav.navbar-nav.navbar-left
    %li= link_to "Dashboard", admins_dashboard_path
    %li= link_to "Basic", admins_applicant_status_path(status: 'basic')
    %li= link_to "DRT", admins_applicant_status_path(status: 'drt')
    %li= link_to "Video", root_path
    %li= link_to "Interview", admins_interview_path
    %li= link_to "Simulation", root_path
    %li= link_to "Contract", root_path
    %li= link_to "Approved", root_path
    %li= link_to "Enrolled", root_path
    .search-input-main
      = form_with scope: :search, url: admins_applicant_search_path, local: true do |form|
        = form.text_field :search_term, class: 'search-field', placeholder: 'Search...'
      -# %form.form-search.form-horizontal.pull-right
      -#   %input.search-query.input-large{:placeholder => "Search...", :type => "text"}

app/views/admins/applicants/dashboard.html.haml
= render 'applicant_table'

app/views/admins/applicants/dashboard_filter.html.haml
= render 'applicant_table'

app/views/admins/applicants/drts_upload.html.haml
= semantic_form_for user_drt, local: true do |f|
  = f.hidden_field :drt  
  = f.file_field :drt
  = f.submit

app/views/admins/applicants/search.html.haml
= render 'applicant_table'

app/views/admins/applicants/show.html.haml
.container.applicant-container
  .table-responsive.transparent-container.applicant-profile
    .name-picture-container
      %h2= @applicant.first_name + ' ' + @applicant.last_name
      .applicant-profile-picture
        -if @applicant.profile_picture
          = image_tag @applicant.profile_picture.image.url
        -else
          = image_tag('img_placeholder.png')
    %table.table.applicant-profile-table
      %thead
        %tr
          %th Details
          %th
          %th When
        %tr
          %td Email
          %td= @applicant.email_address
          %td= @applicant.updated_at
        %tr
          %td Phone number
          %td= @applicant.phone_number
          %td= @applicant.updated_at
        %tr
          %td Highest education
          %td= @applicant.highest_education
          %td= @applicant.updated_at
        %tr
          %td English knowledge
          %td= @applicant.english_knowledge
          %td= @applicant.updated_at
        %tr
          %td English class
          -if @applicant.english_class == 'English'
            %td= 'OK'
          -else
            %td= "NO"

          %td= @applicant.updated_at
        %tr
          %td Payment option
          %td= @applicant.payment_option
          %td= @applicant.updated_at
        %tr
          %th Documents
        %tr
          %td
            -if @applicant.profile_picture
              %a{href: @applicant.profile_picture.image.url, download: @applicant.profile_picture.image.url, target: "blank"} Profile picture
            -else
              No profile picture uploaded
          %td
            -if @applicant.cv
              %a{href: @applicant.cv.cv.url, download: @applicant.cv.cv.url, target: "blank"} CV
            -else
              No CV uploaded
          %td
            -if @applicant.drt
              %a{href: @applicant.drt.drt.url, download: @applicant.drt.drt.url, target: "blank"} DRT
            -else
              No DRT uploaded
        %tr
          %td
            -if @applicant.profile_picture && @applicant.profile_picture.upload_state == 'approval_pending'
              = link_to admins_decision_path(applicant_id: @applicant.id, status: 'profile_picture', decision: 'approve'), class: 'btn btn-success approve-button' do
                %span.glyphicon.glyphicon-ok
              = link_to admins_decision_path(applicant_id: @applicant.id, status: 'profile_picture', decision: 'decline'), class: 'btn btn-danger decline-button' do
                %span.glyphicon.glyphicon-remove
          %td
            -if @applicant.cv && @applicant.cv.upload_state == 'approval_pending'
              = link_to admins_decision_path(applicant_id: @applicant.id, status: 'cv', decision: 'approve'), class: 'btn btn-success approve-button' do
                %span.glyphicon.glyphicon-ok
              = link_to admins_decision_path(applicant_id: @applicant.id, status: 'cv', decision: 'decline'), class: 'btn btn-danger decline-button' do
                %span.glyphicon.glyphicon-remove
          %td
        %tr
          %th Comments
          %td
          %td
        %tr
          %td{colspan: '2'}= render template: 'admins/applicants/comments/index'
        %tr
          %td{colspan: '2'}= render template:'admins/applicants/comments/new'