config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # Skip sessions/registration to limit authentication to oauth
  # Signout and sign_in(GET/CREATE) need to be implemented separately.
  # :authenticate_user! redirects user to sign_in GET !
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' },
                     skip: %i[sessions registration]
  as :user do
    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resource :cv, only: [:new, :create, :edit, :update]
  resource :profile_picture, only: [:new, :create, :edit, :update]

  get 'welcome/profile'
  root 'welcome#index'

  namespace :admins  do
    get 'dashboard', to: 'applicants#dashboard', as: 'dashboard'
    get 'dashboard/:status', to: 'applicants#dashboard_filter', as: 'applicant_status'
    resources :applicants, except: [:edit, :index, :destroy, :new, :create, :update] do
      resources :comments
    end
    get 'decision/:status/:decision', to: 'applicants#status_update', as: 'decision'
    post 'search', to: 'applicants#search', as: 'applicant_search'
    resources :options, except: [:show, :index, :destroy],
              path_names: { new: 'new/:category', edit: ':category' } do
      get ':category', to: 'options#filter', as: 'filter', on: :collection
      delete ':category/:id', to: 'options#destroy', as: 'destroy', on: :collection
    end
    resources :drts, only: [:new, :create], path_names: { new: '/', create: 'new/'}
    get 'interview', to: 'interview#new', as: 'interview'
    resources :interview, only: [:create, :edit, :update, :show], path_names: { new: '/', create:'new/'}
  end
  resources :applicants, except: [:edit, :destroy, :update, :show] do
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
      @drt = Drt.all
    end

    def profile
      redirect_to root_path unless current_user
    end
end

app/views/welcome/index.html.haml
.container.welcome-text
  %h1 Welcome!
  - unless current_user
    %p.start-instruction To start please hit the login button!
  - if current_user && current_user.admin
    %p.start-instruction Number of unused DRT hashes: #{@drt.length}
    - if @drt.length < 5
      %p.test-text You have less than 5 DRT hashes, please create at least #{5 - @drt.length} new one(s):
      %p= link_to raw('<strong>CREATE <em>DRT HASHES</em></strong>'), admins_drts_url

app/views/welcome/profile.html.haml
.container
  %h2 Profile
  .table-responsive.transparent-container
    %table.table
      %thead
        %tr
          %th E-mail
      %tbody
        %tr
          %td= current_user.email