config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # Skip sessions/registration to limit authentication to oauth
  # Signout and sign_in(GET/CREATE) need to be implemented separately.
  # :authenticate_user! redirects user to sign_in GET !
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' },
                     skip: %i[sessions registration]
  as :user do
    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resource :cv, only: [:new, :create, :edit, :update]
  resource :profile_picture, only: [:new, :create, :edit, :update]

  get 'welcome/profile'
  root 'welcome#index'

  namespace :admins  do
    get 'dashboard', to: 'applicants#dashboard', as: 'dashboard'
    get 'dashboard/:status', to: 'applicants#dashboard_filter', as: 'applicant_status'
    resources :applicants, except: [:edit, :index, :destroy, :new, :create, :update] do
      resources :comments
    end
    get 'decision/:status/:decision', to: 'applicants#status_update', as: 'decision'
    post 'search', to: 'applicants#search', as: 'applicant_search'
    resources :options, except: [:show, :index, :destroy],
              path_names: { new: 'new/:category', edit: ':category' } do
      get ':category', to: 'options#filter', as: 'filter', on: :collection
      delete ':category/:id', to: 'options#destroy', as: 'destroy', on: :collection
    end
    resources :drts, only: [:new, :create], path_names: { new: '/', create: 'new/'}
    get 'interview', to: 'interview#new', as: 'interview'
    resources :interview, only: [:create, :edit, :update, :show], path_names: { new: '/', create:'new/'}
  end
  resources :applicants, except: [:edit, :destroy, :update, :show] do
  end
end

app/models/option.rb
class Option < ApplicationRecord
end

app/controllers/admins/options_controller.rb
class Admins::OptionsController < Admins::AdminController
  include OptionsHelper

  def filter
    @options = Option.where(['category = ?', category])
  end

  def new
    @option = Option.new
  end

  def edit
    @option = Option.find(params[:id])
  end

  def create
    @option = Option.create(option_params)
    if @option.errors.any?
      render 'new'
    else
      redirect_to filter_admins_options_path(category: category)
    end
  end

  def update
    @option = Option.find(params[:id])
    if @option.update(option_params)
      redirect_to filter_admins_options_path(category: category)
    else
      render 'edit'
    end
  end

  def destroy
    Option.find(params[:id]).delete
    redirect_to filter_admins_options_path(category: category)
  end

  private

  def option_params
    params.require(:option).permit(:category, :name, :message)
  end
end

app/helpers/options_helper.rb
module OptionsHelper
  def category
    params[:category] || params[:option][:category]
  end
end

app/views/admins/options/_form.html.haml
= semantic_form_for [:admins, @option], local: true do |f|
  = f.hidden_field :category, value: category 
  = f.input :name
  = f.input :message
  = f.submit

app/views/admins/options/_header.html.haml
.navbar.navbar-default
  %ul.nav.navbar-nav.navbar-left
    %li= link_to 'Payment', filter_admins_options_path(category: 'payment')
    %li= link_to 'Language', filter_admins_options_path(category: 'english_level')
    %li= link_to 'Education', filter_admins_options_path(category: 'education')
    %li= link_to 'Interview', filter_admins_options_path(category: 'interview')
    %li= link_to 'DRT hash', admins_drts_path

app/views/admins/options/edit.html.haml
.container.admin-settings
  .transparent-container
    = render 'shared/error-messages', model: @option
    = render 'form'

app/views/admins/options/filter.html.haml
.container.admin-settings
  .transparent-container
    %table.table.table-hover
      %thead
        %tr
          %td
          %td Category
          %td Message
          %td
          %td
      %tbody
        - @options.each_with_index do |option, i|
          %tr
            %td= i + 1
            %td= option.name
            %td= option.message
            %td
              = link_to edit_admins_option_path(id: option.id, category: category) do
                %span.glyphicon.glyphicon-pencil.btn-primary
            %td
              = link_to destroy_admins_options_path(category: category, id: option.id), class:'confirm-delete', method: :delete, data: { confirm: 'Are you sure?' }  do
                %span.glyphicon.glyphicon-trash.btn-danger


    %div.fluid-container
      = link_to 'Add', new_admins_option_path(category: category), class: 'btn btn-primary'

app/views/admins/options/new.html.haml
.container
  %h1 Add new #{category} option
  .transparent-container
    = render 'shared/error-messages', model: @option
    = render 'form'